In [1]:
import numpy as np

In [4]:
a = np.array([2,23,4])
print(a)

[ 2 23  4]


In [8]:
a = np.array([2,23,4],dtype = np.int)
print(a.dtype)

int32


In [9]:
a = np.array([[2,23,4],
              [2,32,4]])
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [10]:
a = np.zeros((3, 4))
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [11]:
a = np.ones((3, 4), dtype = np.int16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
a = np.arange(10, 20, 2)#2为步长
print(a)

[10 12 14 16 18]


In [13]:
a = np.arange(12).reshape((3, 4)) #3行4列，数组
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
a = np.linspace(1, 10, 5) #将1到10分成5段
print(a)

[  1.     3.25   5.5    7.75  10.  ]


In [18]:
a = np.linspace(1, 10, 6).reshape((2, 3))
print(a)

[[  1.    2.8   4.6]
 [  6.4   8.2  10. ]]
