In [4]:
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.arange(4)
c = a - b
d = b**3 #3次方
print(c,d)

[10 19 28 37] [ 0  1  8 27]


In [5]:
c = 10*np.sin(a) #cos tan相同
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [6]:
print(b)
print(b == 3) #也可以判断 < 和 >

[0 1 2 3]
[False False False  True]


In [7]:
a = np.array([[1, 1],
              [0, 1]])
b = np.arange(4).reshape((2, 2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [9]:
c = a*b #逐个运算
c_dot = np.dot(a, b) #矩阵运算
c_dot2 = a.dot(b)    #矩阵运算
print(c)
print(c_dot)
print(c_dot2)

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [11]:
a = np.random.random((2, 4)) #生成随机数列
print(a)

[[ 0.9504401   0.7170617   0.75202897  0.60994675]
 [ 0.62137283  0.59322387  0.63558322  0.54401067]]


In [13]:
print(np.sum(a))
print(np.sum(a, axis = 1)) #每一行（1）中进行相应处理（求和）
print(np.sum(a, axis = 0)) #每一列（0）中进行相应处理（求和）
print(np.min(a))
print(np.max(a))

5.42366811477
[ 3.02947753  2.39419059]
[ 1.57181293  1.31028557  1.38761219  1.15395743]
0.544010671454
0.950440099432
