In [1]:
import numpy as np

In [11]:
A = np.arange(2, 14).reshape((3, 4))
print(A)
print(np.argmin(A))
print(np.argmax(A))
print(np.mean(A))  #平均值 
print(A.mean())
print(np.average(A))
print(np.median(A))#中位数

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
7.5


In [12]:
print(np.cumsum(A))#累加（第三个是前面三个的值）
print(np.diff(A))  #累差（此数与前面一个数的差值）
print(np.sort(A))  #排序（每一行从小到大排序）
print(np.transpose(A)) #矩阵转置
print(A.T)             #矩阵转置

[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [13]:
print(np.clip(A, 5, 9)) #5为最小值 9为最大数（大于9变成9）

[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [15]:
print(np.mean(A, axis = 0)) #aixs = 0对于列进行计算平均值

[ 6.  7.  8.  9.]
