In [1]:
import numpy as np

In [2]:
A = np.arange(3, 15) #一维
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
print(A[3])

6


In [5]:
A = np.arange(3, 15).reshape((3, 4))   #二维
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [6]:
print(A[2])   #索引行数

[11 12 13 14]


In [7]:
print(A[1][1])  #对8的索引方式一

8


In [8]:
print(A[1, 1])  #对8的索引方式二

8


In [9]:
print(A[2, :])  #对3行的索引

[11 12 13 14]


In [10]:
print(A[:, 1])  #对第二列

[ 4  8 12]


In [11]:
print(A[1, 1:3]) #对第二行2至4列索引

[8 9]


In [12]:
for row in A:
    print(row)  #打印每一行

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [13]:
for column in A.T:
    print(column)  #输入列

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [15]:
print(A.flatten())
for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
