In [1]:
import numpy as np

In [9]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

In [17]:
C = np.vstack((A, B))  #vertical stack 垂直
D = np.hstack((A, B))  #horizontal stack左右
print(C)
print(D)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [18]:
print(A.shape, C.shape, D.shape)

(3,) (2, 3) (6,)


In [23]:
print(A[np.newaxis, :]) #行中添加维度
print(A[np.newaxis, :].shape)
print(A[:, np.newaxis]) #列中添加维度
print(A[:, np.newaxis].shape)

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [27]:
A = np.array([1, 1, 1])[:, np.newaxis]
B = np.array([2, 2, 2])[:, np.newaxis]
print(A)
print(B)


[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]


In [30]:
C = np.concatenate((A, B, B, A), axis = 0) #列（上下这个维度）合并
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
