In [1]:
import numpy as np

In [3]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [4]:
b = a
c = a 
d = b

In [5]:
a[0] = 11
print(a)

[11  1  2  3]


In [8]:
print(b, d)
b is a

[11  1  2  3] [11  1  2  3]


True

In [9]:
d[1:3] = [22, 33] #改变的是第一个和第2个数
print(d)

[11 22 33  3]


In [10]:
print(a)          #a的值也相应的发生改变

[11 22 33  3]


In [11]:
e = a.copy()      #不想让e关联e deep copy
a[0] = 1
print(a)
print(e)

[ 1 22 33  3]
[11 22 33  3]
